//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Buisson.h
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#if !defined(_BUISSON_H)
#define _BUISSON_H

#include "Immobile.h"
#include "Ressource.h"

class Buisson : public Immobile, public Ressource
{
public:
	void Buisson();
};

#endif  //_BUISSON_H
