//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Buisson.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "Buisson.h"

void Buisson::Buisson()
{

}

