//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Enfant.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "Enfant.h"

void Enfant::Enfant()
{

}

