//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Femme.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "Femme.h"

void Femme::Femme()
{

}

