//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Immobile.h
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#if !defined(_IMMOBILE_H)
#define _IMMOBILE_H

#include "Ressource.h"

class Immobile : public Ressource
{
};

#endif  //_IMMOBILE_H
