//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Lapin.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "Lapin.h"

void Lapin::Lapin()
{

}

