//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MembreDuPeuple.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "MembreDuPeuple.h"

void MembreDuPeuple::MembreDuPeuple()
{

}

void MembreDuPeuple::setPV()
{

}

void MembreDuPeuple::setAge()
{

}

void MembreDuPeuple::setEsperanceDeVie()
{

}

