//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Mobile.h
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#if !defined(_MOBILE_H)
#define _MOBILE_H

#include "Ressource.h"

class Mobile : public Ressource
{
private:
	int vitesseDeDeplacement;
public:
	void Mobile();
	void seDeplacer();
};

#endif  //_MOBILE_H
