//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Peuple.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "Peuple.h"

void Peuple::Peuple()
{

}

void Peuple::getNbrElement()
{

}

void Peuple::getQteRessource()
{

}

void Peuple::setNbrElement()
{

}

void Peuple::setQteRessource()
{

}

