//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ressource.cpp
//  @ Date : 11/03/2013
//  @ Author : Xavier chalut
//
//


#include "Ressource.h"

void Ressource::Ressource()
{

}

